# Generated by Django 4.2.11 on 2024-03-20 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='text',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='parent_menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.menu'),
        ),
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.CharField(default='ee', max_length=255),
            preserve_default=False,
        ),
    ]
